export const aboutUsText = {
    en: "SOSAnimals Moldova was formed in December of 2017 and has grown from a just few members to over 2,600 participants since that time. SOSAnimals Moldova focuses their efforts solely on funding unpaid volunteers, allowing them to afford the TNR programs that are so essential to situations like the one in Chisinau. Volunteers are responsible for all incurred costs aside from the sterilization procedure itself. These include the trapping, housing, feeding, transport, and additional medical care the animals receive throughout the TNR process. \\n SOSAnimals Moldova was founded due to the absence of government policy in places like Chisinau. The issue of disorganization and decentralization has made it difficult to manage and distribute funds to the volunteers in the past, causing programs to be run in a haphazard fashion. \\n\n" +
        "\n" +
        "Having a centralized group means better reporting and transparency are possible, along with more efficient management, equaling a more effective force against the serious stray animal problem in places like Chisinau.\n" +
        "\n" +
        "As of July 2021, SOSAnimals Moldova has officially helped to sterilize 2,783 stray animals, including 695 dogs and 2,088 cats — and it can only get better with more help.",
    ro: "SOSAnimals Moldova a fost înființată în decembrie 2017 și a crescut de la doar câțiva membri la peste 2.600 de participanți de atunci. SOSAnimals Moldova își concentrează eforturile exclusiv pe finanțarea voluntarilor neplătiți, permițându-le să-și permită programele TNR atât de esențiale în situații precum cel de la Chișinău. Voluntarii sunt responsabili pentru toate costurile suportate, în afară de procedura de sterilizare în sine. Acestea includ capcana, adăpostirea, hrănirea, transportul și îngrijirea medicală suplimentară pe care animalele le primesc pe parcursul procesului TNR. SOSAnimals Moldova a fost fondată din cauza absenței politicii guvernamentale în locuri precum Chișinău. Problema dezorganizării și descentralizării a făcut dificilă gestionarea și distribuirea fondurilor către voluntari în trecut, determinând ca programele să fie derulate într-un mod întâmplător.\n" +
        "\n" +
        "A avea un grup centralizat înseamnă o raportare mai bună și o transparență mai bună, împreună cu un management mai eficient, echivalând cu o forță mai eficientă împotriva problemei grave a animalelor fără stăpân din locuri precum Chișinău.\n" +
        "\n" +
        "Începând cu iulie 2021, SOSAnimals Moldova a ajutat oficial la sterilizarea a 2.783 de animale fără stăpân, inclusiv 695 de câini și 2.088 de pisici – și se poate îmbunătăți doar cu mai mult ajutor.",
    ru: "SOSAnimals Moldova была создана в декабре 2017 года и с тех пор выросла с нескольких членов до более чем 2600 участников. SOSAnimals Moldova фокусирует свои усилия исключительно на финансировании неоплачиваемых волонтеров, что позволяет им позволить себе программы TNR, которые так необходимы в ситуациях, подобных той, что произошла в Кишиневе. Волонтеры несут ответственность за все понесенные расходы, кроме самой процедуры стерилизации. К ним относятся отлов, содержание, кормление, транспортировка и дополнительная медицинская помощь, которую животные получают на протяжении всего процесса TNR. SOSAnimals Moldova была основана из-за отсутствия государственной политики в таких местах, как Кишинев. Проблема дезорганизации и децентрализации затрудняла управление и распределение средств среди волонтеров в прошлом, что приводило к тому, что программы выполнялись бессистемно.\n" +
        "\n" +
        "Наличие централизованной группы означает, что возможна лучшая отчетность и прозрачность, наряду с более эффективным управлением, что равняется более эффективной силе против серьезной проблемы бездомных животных в таких местах, как Кишинев.\n" +
        "\n" +
        "По состоянию на июль 2021 года SOSAnimals Moldova официально помогла стерилизовать 2 783 бездомных животных, в том числе 695 собак и 2 088 кошек, и с дополнительной помощью ситуация может стать только лучше."
}
